### PR TITLE
Stage 2 — Markup & JSX

### PR DESCRIPTION
**Pull request by hotcheetoqueen**

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Jessica!

Good job! Some corrections need to be made, but on the whole, the project looks quite good.

~Please note that the dev version fails to open: https://prnt.sc/1183sgx. Please, fix.~

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* ~The content of the page should have limited width. Currenlty, on large screen resolutions, it's stretched to the whole width (e.g. on 2800px the header and footer will occupy the whole screen width).~
* ~Incorrect font-family for most elements https://prnt.sc/11849qb https://prnt.sc/1184ach https://prnt.sc/1184dio https://prnt.sc/1184dyo https://prnt.sc/1184ee8 https://prnt.sc/1184fza, please correct similar issues everywhere in the project~
* ~Incorrect layout of a card on "Home" page: https://prnt.sc/1184bkr. The keyword should be in the left upper corner only on "Saved articles" page. "Remove from saved" should appear only in hover. Line-height of `news-card__description` is incorrect~
* ~https://prnt.sc/1184gn6  There should be three cards in a row on tablet and desktop resolutions.~
* ~The content isn't centered: https://prnt.sc/1184hzr~
* ~Horizontal scroll on 321 - 477, 521 - 727~
* ~Incorrect layout in header on saved-news: https://prnt.sc/1184q9b~
* ~Layout of "registration successful" popup: https://prnt.sc/1184u86~

~Haven't been able to check the layout of the header on home page, when the user is logged in. Preloader and "Nothing found" states too. Please, let me know how I can check it.~ (Added to Readme!)

- [x]  ~All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
Menu doesn't open on mobile screens.~

- [x]  ~The layout is responsive and displays correctly at all intermediate resolutions.
Horizontal scroll and broken layout on intermediate resolutions: https://prnt.sc/1184j4b. This is just an example, it's necessary to check the layout on intermediate resolutions carefully, it should stay consistent on any screen from 320 and higher.~

- [x]  ~There are no validation errors.
`div` can;t be used inside `ul`: https://prnt.sc/1184zjc~

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  ~The popup windows have opening and closing functionality implemented.
Sign up popup isn't opened on clicking the link on "sign in" popup
Menu doesn't open on mobile screens.~

- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [ ]  Classes are named according to BEM specifications.
https://prnt.sc/1184yns - the elements are used outside of its block and block is nested inside its element. Please, correct all similar issues.

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  ~Form elements should be highlighted when focused.
Search form input isn't highlighted~

- [x]  The form must have placeholders, and required fields should be validated.
~Fields aren't validated, the inputs don't have attribute `required`~

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  ~System fonts are connected as alternatives to each of your fonts.
https://prnt.sc/11854f4 - Please, find and correct all similar issues.~
- [x]  ~Raster and vector images have been optimized.~

## Number of points:  41

**Comment by hotcheetoqueen** [comment]
Hi @ImaliaNsk, my updates are in! Please note, I added info about how to test special components like preloader/not found empty state in the readme. I also crossed out things as I worked on them so you can see which items were checked off by you versus as I completed them. Thanks so much for your time and help!

**Comment by ImaliaNsk** [comment]
Hi! Thanks for the corrections, good job! However, some issues are still left to work on, card layout for different states, and the responsive design will require the most attention. Other issues are minor, and hopefully will be easy to fix. Please, note that hamburger menu should open on a mobile screens. Good luck!

# Project review summary:
### Performance Criteria
- [x]  ~The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.~

* ~Only one link should be underlined in the navigation: https://prnt.sc/11ajz2r https://prnt.sc/11ajzn3~
* ~Also, on saved-news header there also should be a gray bottom line, as on a home page, and button to sign out should have an icon on it.~
* ~Incorrect layout of a card on "saved-news" page: https://prnt.sc/11ak0yd. The keyword should be in the left upper corner, and the icon to remove the card from saved should be in the right upper corner. "Remove from saved" should appear only in hover. Line-height of `news-card__description` is incorrect~
* ~A horizontal scroll on desktop resolutions (1201 - 1291, 1440 - 1456): https://prnt.sc/11ak3l7. Please fix. Remeber that it can't be hidden with `overflow: hidden` (this is in 'logged in' state)~
* ~Horizontal scroll on 601 - 645, 801 - 905 (this is in 'logged in' state) https://prnt.sc/11alagu~
* ~Layout of "registration successful" popup: https://prnt.sc/11akvhr~

- [x]  ~All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.~
~* Menu should open on mobile screens.~

- [x]  ~The layout is responsive and displays correctly at all intermediate resolutions.~
~Horizontal scroll and broken layout on intermediate resolutions: https://prnt.sc/1184j4b. This is just an example, it's necessary to check the layout on intermediate resolutions carefully, it should stay consistent on any screen from 320 and higher. (Zoom out for small whitespace= horizontal scroll):
image~
* ~Horizontal scroll on 601 - 645, 801 - 905 [mentioned twice, handling above] (this is in 'logged in' state)~
- [x]  ~There are no validation errors.~
~* https://prnt.sc/11al34o https://prnt.sc/11al3pr~
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  ~The popup windows have opening and closing functionality implemented.~
~* Menu doesn't open on mobile screens.~
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [ ]  Classes are named according to BEM specifications.
https://prnt.sc/11al4vr - the elements are used outside of its block, the same with 'popup__container'. Please, correct all similar issues.
- [x]  ~Buttons, input fields, and links are implemented in all of the states specified in the design.~
~* The bookmark on the card should have `Sign in to save articles` on hover, and the remove icon in "saved-article" should have "Remove from saved" on hover.~
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  ~System fonts are connected as alternatives to each of your fonts.
https://prnt.sc/11al6fc - Please, find and correct all similar issues.~
- [x]  Raster and vector images have been optimized.

## Number of points: 44

**Comment by hotcheetoqueen** [comment]
Hi @ImaliaNsk, my updates are in! Please note, I added info about how to test special components like preloader/not found empty state & how to test loggedIn state in the readme. I also crossed out things as I worked on them so you can see which items were checked off by you versus by me as I completed them. Thanks so much for your time and help!

**Comment by ImaliaNsk** [comment]
Hi! Perfect work, congratulations, the project is accepted! Good luck on the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [ ]  The popup windows have opening and closing functionality implemented.
It's impossible to close the popup on mobile screens: https://prnt.sc/11nabo8
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.
	
### Best Practices
- [ ]  Classes are named according to BEM specifications.
BEM entity can't be a block and its own eement at the same time: https://prnt.sc/11nakgu
Should be key-value modifiers, not boolean https://prnt.sc/11nanh9
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 95

**Pull request merged**
